### ISSUE TITLE
Discussion: dirty hack for client-side

### ISSUE THREAD

**Issue by fatawesome** [telenko/node-mf-example#2]
Hey, thanks for the library! I'm trying to setup federated SSR with Vue and having bad luck with the [same place you implemented this obscure stuff](https://github.com/telenko/node-mf-example/blob/ad8b1283fc9cd6f1de28c8fd06bb6507755b308b/host/next.config.js#L14). Just wanted to ask if you had any luck fixing it in a normal way? 

The error I'm getting is about eager consumption (the same if use normal url instead of hack in your example).

**Comment by telenko** [comment]
Hi,

oh yes - that issue is a real pain. I don't have good solution, but i can
recommend taking a look at this library:

***@***.***/nextjs-mf
(but last time i was trying it together with my node-mf there was no luck).

I was planning to fix it or make another useful plugin for webpack5, but
for now nothing :(

Hope it helps.


пн, 26 лип. 2021, 16:57 користувач Ilya Alonov ***@***.***>
пише:

**Comment by fatawesome** [comment]
Thanks! Btw, maybe you did some research on the problem? Unfortunately, from first several hours spent I did not get any result :D

**Comment by Kinbaum** [comment]
Hey, I have a solution for that. You can do something like this:
``` js
remotes: {
    remoteLib: isServer
        ? "remoteLib@http://localhost:3002/node/remoteEntry.js"
        : "remoteLib@http://localhost:3002/web/remoteEntry.js"
}
```

Then you can add a custom loader to test for `_app.js` so that you can attach the [share scope at runtime](https://webpack.js.org/concepts/module-federation/#dynamic-remote-containers).
This gets around the `globalThis` problem. 

The only thing here is that the semver checks don't seem to work. 
The host and remote have to be on identical versions.

**Comment by fatawesome** [comment]
I will close this issue/discussion, as it seems to be solved :)
